---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1589942/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R Admin $DEPLOYPATH
    # - /bin/cp -R User $DEPLOYPATH
    
